# -*- coding: utf-8 -*-
"""image_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYpwqX6q9e-04zRuffZhJqQsp1LhD8AP
"""

import re

def extract_day_from_path(path):
    # find ALL d<number> patterns
    matches = re.findall(r"d(\d+)", path)

    if len(matches) == 0:
        return None

    # take first valid occurrence
    return int(matches[0])


def get_mask_for_day(mask_list, day):

    filtered = []

    for m in mask_list:
        file_day = extract_day_from_path(m)

        if file_day is not None and file_day == day:
            filtered.append(m)

    if len(filtered) == 0:
        print("❌ No mask found for day:", day)
        print("👉 Available sample paths:")
        print(mask_list[:5])
        return None

    print(f"✅ Found {len(filtered)} masks for day {day}")
    return sorted(filtered)[0]

image = pipe(
    prompt= prompt,
    negative_prompt="distorted, deformed, extra leaves, roots visible,non green leaves",
    image=mask,   # 🔥 THIS IS THE KEY
    guidance_scale=10,
    num_inference_steps=50,
    controlnet_conditioning_scale=1.8
).images[0]
plt.imshow(image)
plt.axis("off")