# -*- coding: utf-8 -*-
"""load_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eopmHb0mwPZI9W7f3Lkadc8FdPx1pfdN
"""

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline
import torch

device = "cuda"

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-seg",
    torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16
).to(device)

pipe.enable_model_cpu_offload()

# load your trained LoRA
pipe.load_lora_weights("/content/drive/MyDrive/radish_lora_model/checkpoint-3400")

print("✅ Ready for mask-based generation")