# -*- coding: utf-8 -*-
"""Mask_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACzexbkkO7jGsiieYltfBuvvdmUKl8To
"""

# ==============================
# 🌿 MASK GENERATION (RECURSIVE)
# ==============================

import os
import cv2
from tqdm import tqdm

# 🔁 ROOT PATH (EDIT THIS)
root_dir = "/content/drive/MyDrive/p3"

# mask output root
mask_root = "/content/drive/MyDrive/p3_maskssss"

os.makedirs(mask_root, exist_ok=True)

# collect all image paths
image_paths = []

for root, dirs, files in os.walk(root_dir):
    for file in files:
        if file.lower().endswith((".png", ".jpg", ".jpeg")):
            image_paths.append(os.path.join(root, file))

print(f"Total images found: {len(image_paths)}")

# ==============================
# 🔥 PROCESS ALL IMAGES
# ==============================

for img_path in tqdm(image_paths):

    # read image
    img = cv2.imread(img_path)
    if img is None:
        continue

    # convert to HSV
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # 🟢 green detection (tune if needed)
    lower_green = (25, 40, 40)
    upper_green = (85, 255, 255)

    mask = cv2.inRange(hsv, lower_green, upper_green)

    # 🔥 clean mask
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_DILATE, kernel)

    # ==============================
    # SAVE WITH SAME STRUCTURE
    # ==============================

    relative_path = os.path.relpath(img_path, root_dir)
    mask_path = os.path.join(mask_root, relative_path)

    os.makedirs(os.path.dirname(mask_path), exist_ok=True)

    cv2.imwrite(mask_path, mask)

import re
import random
import glob

# -----------------------------
# EXTRACT DAY FROM PROMPT
# -----------------------------
def get_day_from_prompt(prompt):

    match = re.search(r"day\s*(\d+)", prompt.lower())

    if match:
        return int(match.group(1))

    return None


# -----------------------------
# GET RANDOM MASK FOR THAT DAY
# -----------------------------
def get_mask_for_day(mask_list, day):

    filtered = [m for m in mask_list if f"/d{day}/" in m]

    if len(filtered) == 0:
        return None

    return random.choice(filtered)


# -----------------------------
# LOAD ALL MASKS
# -----------------------------
mask_list = glob.glob(
    "/content/drive/MyDrive/p2_512_masks/**/*.png",
    recursive=True
)

print("✅ Total masks:", len(mask_list))

import cv2
from PIL import Image
import matplotlib.pyplot as plt

import glob

p2_masks = glob.glob("/content/drive/MyDrive/p2_512_masks/**/*.*", recursive=True)
p3_masks = glob.glob("/content/drive/MyDrive/p3_maskssss/**/*.*", recursive=True)

all_masks = p2_masks + p3_masks

print("Total masks:", len(all_masks))

import random

def get_masks_for_day(mask_list, day):
    day_str1 = f"d{day}"
    day_str2 = f"day_{day}"

    return [p for p in mask_list if (day_str1 in p or day_str2 in p)]


def get_random_mask(mask_list, day):
    candidates = get_masks_for_day(mask_list, day)

    if len(candidates) == 0:
        return None

    return random.choice(candidates)

import re

def get_day_from_prompt(prompt):
    match = re.search(r"day\s*(\d+)", prompt.lower())

    if match:
        return int(match.group(1))

    return None

def get_day_from_prompt(prompt):
    match = re.search(r"day\s*(\d+)", prompt.lower())
    if match:
        return int(match.group(1))
    return None

import re

def extract_day_from_path(path):
    # find ALL d<number> patterns
    matches = re.findall(r"d(\d+)", path)

    if len(matches) == 0:
        return None

    # take first valid occurrence
    return int(matches[0])


def get_mask_for_day(mask_list, day):

    filtered = []

    for m in mask_list:
        file_day = extract_day_from_path(m)

        if file_day is not None and file_day == day:
            filtered.append(m)

    if len(filtered) == 0:
        print("❌ No mask found for day:", day)
        print("👉 Available sample paths:")
        print(mask_list[:5])
        return None

    print(f"✅ Found {len(filtered)} masks for day {day}")
    return sorted(filtered)[0]