# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPjGlAygtxWXH_6R-_mvWLk1XLJUB056
"""

from PIL import Image
import cv2
import matplotlib.pyplot as plt


prompt="radish plant in white pot with soil at day 26"

day = get_day_from_prompt(prompt)
print("Detected day:", day)

mask_path = get_random_mask(all_masks, day)

if mask_path is None:
    raise ValueError("No mask found — check dataset naming")

print("Using mask:", mask_path)

mask = cv2.imread(mask_path, 0)
mask = cv2.resize(mask, (512, 512))
mask = Image.fromarray(mask).convert("RGB")

import matplotlib.pyplot as plt
plt.imshow(mask)
plt.title("Random Mask")
plt.axis("off")

