# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oneIvM-qdXgrZBfiaIHgDSUDMrXt5wq1
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q diffusers transformers accelerate datasets peft bitsandbytes
!pip install -q git+https://github.com/huggingface/diffusers

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/huggingface/diffusers
# %cd diffusers/examples/text_to_image
!pip install -r requirements.txt

!pip install clean-fid