# -*- coding: utf-8 -*-
"""lora_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcfRX_oYBQpxwkjcD81Y9CpHnlWA-31d
"""

!accelerate launch train_text_to_image_lora.py \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --train_data_dir="/content/drive/MyDrive/p2_512" \
  --caption_column="text" \
  --resolution=512 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --max_train_steps=6000 \
  --checkpointing_steps=200 \
  --resume_from_checkpoint="checkpoint-3400" \
  --output_dir="/content/drive/MyDrive/radish_lora_model" \
  --mixed_precision="fp16"